### ISSUE TITLE
Add CANCELLING state

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#103]
Still to be discussed was the question on Section 7.10. State
- Should we add a "CANCELING" state to reflect the fact that the request to cancel has been received but is still being processed?

**Comment by briandoconnor** [comment]
See pull request https://github.com/ga4gh/workflow-execution-service-schemas/pull/104

**Comment by jaeddy** [comment]
Haven't confirmed that any implementations support this, but it's in the spec.

**Comment by geoffjentry** [comment]
@jaeddy thanks for poking at this, just yesterday I was lamenting that there was no `CANCELLING`, perhaps I should have taken a look at the contemporary spec :)

**Comment by jaeddy** [comment]
Just make sure you spell it `CANCELING` ;-)

**Comment by geoffjentry** [comment]
oh good gravy ....
