### ISSUE TITLE
Readme Build Unknown and Error message

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#111]
At the top of the readme at 
https://github.com/ga4gh/workflow-execution-service-schemas/blob/develop/README.md 

there is a Build UNKNOWN and Error (in red) items.

**Comment by jaeddy** [comment]
Working on resolving this. Will plan to use TravisCI build and Swagger validator badges in the README to specifically to statuses for the `develop` branch — that way badges in the default repo view aren't dependent on merging to `master`.

**Comment by jaeddy** [comment]
Fixed in #112 (but will re-open if #115 breaks it for some reason).
