### ISSUE TITLE
Swagger UI and Swagger Editor links in README.rst does not work

### ISSUE THREAD

**Issue by juhtornr** [ga4gh/workflow-execution-service-schemas#139]
I noticed that Swagger UI and Swagger Editor links in README does not work. Swagger UI gives 404 and Swagger UI reports syntax error: 

`"Fetch error undefined https://ga4gh.github.io/workflow-execution-service-schemas/swagger.yaml Jump to line 33"`

The build badge says that the OpenAPI should be valid though. This happens both in `master` and in `develop` branches.

**Comment by jaeddy** [comment]
Thanks @juhtornr — this has been on my to-do list to fix. I'll see if I can get it taken care of on my flight to Boston. 🙂

**Comment by ekalosak** [comment]
@jaeddy the [https://ga4gh.github.io](https://ga4gh.github.io) link 404s - is this something volunteer contributors can fix?

**Comment by denis-yuen** [comment]
https://ga4gh.github.io/workflow-execution-service-schemas/docs/ works so I'm thinking that this is some form of configuration issue along these lines https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by jaeddy** [comment]
The README has been updated to reflect the latest docs build system introduced by #150 and #151, based on [gh-openapi-docs](https://github.com/ga4gh/gh-openapi-docs). Closing this for now.
