### ISSUE TITLE
README to reflect Nextflow support?

### ISSUE THREAD

**Issue by ghost** [ga4gh/workflow-execution-service-schemas#141]
Our organization primarily uses Nextflow. It's my understanding that Nextflow is now an officially supported execution engine in TRS/WES/TES ecosystem. Can the README please be updated to reflect this? 

I have people citing "CWL and WDL support only" as a reason why we would not participate in GA4GH.

Thank you.

**Comment by jaeddy** [comment]
Hi @HashRocketSyntax — thanks for surfacing this issue! We're currently planning an overhaul of our documentation (including the README), and will make sure to clarify support for Nextflow in the process.
