### ISSUE TITLE
https://ga4gh.cloud does not resolve

### ISSUE THREAD

**Issue by ekalosak** [ga4gh/workflow-execution-service-schemas#142]
`curl https://ga4gh.cloud` hangs - is the firewall open at port 80? Or is there another issue?

**Comment by denis-yuen** [comment]
https://ga4gh.github.io/workflow-execution-service-schemas/docs/ works so I'm thinking that this is some form of configuration issue along these lines https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site

**Comment by jaeddy** [comment]
Seems to be working now (note: https://ga4gh.cloud redirects to https://github.com/ga4gh/wiki/wiki).
