### ISSUE TITLE
Please tag the published version

### ISSUE THREAD

**Issue by ghost** [ga4gh/workflow-execution-service-schemas#157]
Hello! The published version https://ga4gh.github.io/workflow-execution-service-schemas/docs/#tag/WorkflowExecutionService is at 1.0.1. But this is not tagged or released here. Thank you!

**Comment by jaeddy** [comment]
Thanks @kaushik-work - we have a bit of overdue GH maintenance, including the latest tag/release. Will try to resolve soon.

**Comment by ruchim** [comment]
@jaeddy -- looks like this may be done -- I see a few tags, especially 1.0.0. Thoughts?
