### ISSUE TITLE
Environment specific parameters

### ISSUE THREAD

**Issue by david4096** [ga4gh/workflow-execution-service-schemas#16]
From @mckinsel , should we, or how do we schematize the parameters for requesting resources (disk space, CPU count, memory)? Can this be pushed down to the CWL/WDL?

**Comment by ruchim** [comment]
My 2 cents here are that resources are likely:
a) statically hard coded in the workflow definition or inputs json or 
b) dynamically provisioned through workflow logi
c) or passed in through some configuration file -- alongide the workflow defintion or inputs

I _believe_ these would all fit inside of workflow_params -- https://github.com/ga4gh/workflow-execution-service-schemas/blob/develop/openapi/components/schemas/RunRequest.yaml#L4. Let me know if you disagree or see a different use case, I'd love to know more.

**Comment by patmagee** [comment]
CWL, WDL and Nextflow all provide mechanisms to request compute resources, along with the workflow_attachments and IMO this fits the requirement for this ticket, so closing for now
