### ISSUE TITLE
WES API clients

### ISSUE THREAD

**Issue by cjllanwarne** [ga4gh/workflow-execution-service-schemas#184]
OpenAPI allows one to generate stub clients relatively easily.

As a WES consumer, it would be fantastic to be able to import a WES client from an official source. It would also help make sure everyone is on the same page w.r.t. expected requests/response shapes and service behaviors.

(Note: If there's already a client somewhere and I just missed it -fantastic - let me know!)

**Comment by patmagee** [comment]
@cjllanwarne I do not think there is an officially packaged client. What I have done in the past is use code generation tools with the build tools to create the generated clients via an external link to the openapi. That gives you a bit more flexibility in terms of generating the client then what an "official" client would do. Have you tried doing that?
