### ISSUE TITLE
Proposal: New WES State for Preemption 

### ISSUE THREAD

**Issue by vsmalladi** [ga4gh/workflow-execution-service-schemas#187]
Problem:
Cloud platform support preemption of machines. [TES currently supports](https://github.com/ga4gh/task-execution-schemas/issues/183) this and potentials WES needs a way to understand that state to implement the correct logic of dealing with workflow resubmission

Solution
Add in new state  "Preempted"

Adding @patmagee to weigh in as well

**Comment by patmagee** [comment]
This has been previously approved in TES, I think we should fast track this and vote on its include it in the next release
