### ISSUE TITLE
Clarify how the WES API is used by multiple, independent users sharing a back end

### ISSUE THREAD

**Issue by brucehoff** [ga4gh/workflow-execution-service-schemas#25]
Approaches might include:
1) No fine-grained authorization:  Anyone who can access a WES compliant workflow engine has access to all the workflows in that system;
2) All WES APIs require authentication and the authorized user has access to just the workflow that they created.  When a user asks to 'list all workflows' the list includes just the ones they created;
3) Users can share access to workflows they create with other users.   This may require additional APIs in WES or, alternatively, access control could be deemed out-of-scope for WES.

**Comment by junjun-zhang** [comment]
@brucehoff, as I understand WES API does intend to be used by multiple users. As shown in the current Swagger specification, here is an example of [ErrorResponse](https://github.com/ga4gh/workflow-execution-service-schemas/blob/e320819cba811a281ffa757e0e13bc70cd4c33bb/openapi/workflow_execution_service.swagger.yaml#L30-L37) for unauthorized operation. So, I think it's clear that there should be an authentication/authorization process before a user can call the API endpoints properly.

Indeed, it could be more explicitly documented. Perhaps for example, in this `/workflows ` GET operation, the [summary](https://github.com/ga4gh/workflow-execution-service-schemas/blob/e320819cba811a281ffa757e0e13bc70cd4c33bb/openapi/workflow_execution_service.swagger.yaml#L46-L50) could add something more specific that only workflows are authorized for the current user will be returned.

I feel the same way that access control could be left to the implementers to decide how to handle, and WES specification should be focused on core functionalities.

**Comment by mdmiller53** [comment]
@brucehoff in an implementation i did, i tried a layered approach.  the workflow engine ran on a server, it took requests to start workflows and returned a token that could be used to access that workflow through that workflow API.  whoever called to start the workflow then was responsible for managing that workflow through the token.  so on a different server i implemented a workflow 'user' task, potentially multiple user servers could then use that workflow server

**Comment by brucehoff** [comment]
@mdmiller53 under your approach I wonder how the 'list all workflows' API would work.  E.g., if there are 100 workflows running, but just 5 for *you* (and so you have 5 'tokens') then are you able to 'list all workflows' and see just your 5?  How you pass the 5 tokens via HTTP?

**Comment by jaeddy** [comment]
After a number of discussions, it seems that multitenancy with WES can be enabled through a variety of configurations. While these different scenarios don't necessarily need to be included in the spec, we should provide examples in the documentation.

**Comment by jaeddy** [comment]
@patmagee I think that makes sense. This feels more in the domain of the starter kit efforts, and could eventually make its way into WES _documentation_ (user guides, tutorials, etc.), but I don't see a strong need for having it be part of the spec.
