### ISSUE TITLE
Finalise names for WES

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#34]
A [survey is currently up to determine the naming schema for WES](https://docs.google.com/forms/d/e/1FAIpQLSeZ_EU2wAPxQt_40_XniawS1zlTbU1yt4aMB98cJ90anhbNbw/viewform). This needs to be completed, a decision made and the changes implemented.

**Comment by jaeddy** [comment]
See #32 for a proposed implementation of the change using `Workflow` and `WorkflowRun` object names (choice 4 in the survey).

**Comment by rishidev** [comment]
@jaeddy I'm not sure where the survey results were being collected - @briandoconnor - did these go to you or David G?

**Comment by briandoconnor** [comment]
I shared the survey with you @jaeddy
