### ISSUE TITLE
Setup key-value filtering of workflow list

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#38]
We allow key-value "tags" on workflow runs. These are most useful if the client can filter on them. The current description for "tag_search" is too vague. This adds query parameters tag_key and tag_value and describes their usage more precisely.

[See PR#33 for more info](https://github.com/ga4gh/workflow-execution-service-schemas/pull/33)

**Comment by rishidev** [comment]
#33

**Comment by david4096** [comment]
This seems like it could be out of scope and shouldn't be required for basic workflow execution. A nice-to-have, but are there any use cases that require this?

**Comment by dglazer** [comment]
On today's Cloud WS call, we agreed to defer this work until requirements are clear. For now we'll do #66 instead.

**Comment by ruchim** [comment]
Given that there's been no new comments about bringing this issue back to life -- it may be time to close this issue and re-open when a specific use case comes up.

**Comment by patmagee** [comment]
Closing this issue since there has not been any comments since the last comment about potentially closing this
