### ISSUE TITLE
Workflow for Basel Testbed demo from TopMed

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#48]
For a demonstration of the GA4GH Cloud Work Stream Testbed Interopability Platform in Basel, a workflow is required to be loaded into Dockstore from TopMed

**Comment by rishidev** [comment]
@briandoconnor has shown alignment workflow on a variety of platforms

**Comment by rishidev** [comment]
Public Google Buckets for the SC workflows

**Comment by briandoconnor** [comment]
FYI:

CWL pipeline:

https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/TOPMed_alignment_pipeline_CWL:1.21.0?tab=info

WDL pipeline:

https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline:1.17.0?tab=info

**Comment by cricketsloan** [comment]
@wshands I the right person I think to answer questions on the WDL workflow and can direct questiosns for the CWL workflow

**Comment by jaeddy** [comment]
Multiple workflows (alignment and variant calling) with multiple versions for each (gs:// or https:// inputs) used in testbed. See #86.
