### ISSUE TITLE
Workflow for Basel Testbed demo from HCA

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#49]
For a demonstration of the GA4GH Cloud Work Stream Testbed Interopability Platform in Basel, a workflow is required to be loaded into Dockstore from the Human Cell Atlas Driver Project

**Comment by rishidev** [comment]
SmartSeq2 workflow TBC @mckinsel

**Comment by denis-yuen** [comment]
Might be this one https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info

**Comment by rishidev** [comment]
SmartSeq2 confirmed in Dockstore

**Comment by jaeddy** [comment]
Smartseq2 workflow used in testbed. See #86.
