### ISSUE TITLE
Orchestrator: wire up AGHA WES endpoint

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#50]
For a demonstration of the GA4GH Cloud Work Stream Testbed Interopability Platform in Basel, a WES endpoint is to be set up to be accessible from the to-be-selected orchestrator by AGHA.

**Comment by rishidev** [comment]
Planned Workflow Engines is Cromwell, hosted by Illumina in collaboration with Broad. Timeline looks tight for this to be completed.

**Comment by jaeddy** [comment]
Done. Thanks to @pr80ik at ILMN (Veritas WES endpoint from @tetron could also be included for this).
