### ISSUE TITLE
Orchestrator: wire up TopMed WES endpoint

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#52]
For a demonstration of the GA4GH Cloud Work Stream Testbed Interopability Platform in Basel, a WES endpoint is to be set up to be accessible from the to-be-selected orchestrator by TopMed

**Comment by rishidev** [comment]
Planned WES enpoints for TopMed - are Cromwell (Google), Toil(TBD), and Cromwell (U Chicago "framework services" / HPC). @briandoconnor is there one here to be used for Basel Testbed Demo in particular?

**Comment by jaeddy** [comment]
Jeff's Cromwell WES endpoint for the Broad satisfied this as well as the HCA Driver target.
