### ISSUE TITLE
Orchestrator: wire up HCA WES endpoint

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#53]
For a demonstration of the GA4GH Cloud Work Stream Testbed Interopability Platform in Basel, a WES endpoint is to be set up to be accessible from the to-be-selected orchestrator by HCA

**Comment by rishidev** [comment]
Cromwell on the Google Cloud Platform (inside DCP 'green box')

**Comment by jaeddy** [comment]
Both @mckinsel and @geoffjentry provided WES endpoints that could be considered HCA environments.
