### ISSUE TITLE
Fix schema version

### ISSUE THREAD

**Issue by jaeddy** [ga4gh/workflow-execution-service-schemas#58]
At some point, the schema version listed in the swagger YAML got off track: the latest `develop` branch shows `0.2.2`, even though there's a `0.3.0` release available for the repo.

I've noticed that @david4096 and @natanlao have been doing a lot of work to improve packaging, versioning, building, etc. for the [DOS schemas](https://github.com/ga4gh/data-object-service-schemas) — maybe they could advise here.

**Comment by cricketsloan** [comment]
➤ Abraham Chavez commented:

Included in [65](https://github.com/ga4gh/workflow-execution-service-schemas/pull/65)
