### ISSUE TITLE
Use protobuf/grpc as schema/api format

### ISSUE THREAD

**Issue by buchanae** [ga4gh/workflow-execution-service-schemas#6]
Can I suggest we use Protobuf/gRPC as the primary format for encoding schemas/APIs? The Task schemas did this, with Swagger and client code generated from that, and it worked nicely. This repo seems to be going in a different direction, and it would be nice to stay consistent.

If I understand correctly, ga4gh schemas use the protobuf format: https://github.com/ga4gh/schemas/blob/master/CONTRIBUTING.rst

**Comment by david4096** [comment]
We're migrating towards an OpenAPI first approach that better suits our goals.
