### ISSUE TITLE
Remove server/client

### ISSUE THREAD

**Issue by david4096** [ga4gh/workflow-execution-service-schemas#60]
The server and client in this repo are aspirational and should be removed and replaced with the workflow-service's server and client, or a simpler demo server should be provided for creating progress on the schemas.

https://github.com/ga4gh/workflow-execution-service-schemas/blob/develop/python/ga4gh/wes/controllers.py

https://github.com/common-workflow-language/workflow-service

**Comment by jaeddy** [comment]
I vote we go with option B:

> a simpler demo server should be provided for creating progress on the schemas

(or something like it)

Will add this to the TODO list for v1.1.
