### ISSUE TITLE
contact_info incorrectly indented in workflow_execution_service.swagger.yaml

### ISSUE THREAD

**Issue by pr80ik** [ga4gh/workflow-execution-service-schemas#62]
Branch: develop (67729e4).

The `workflow_execution_service.swagger.yaml` cannot be processed through swagger-cli because of the following error. The bug does not appear in d1cb6aa

```bash
./node_modules/.bin/swagger-cli validate workflow-execution-service-schemas/openapi/workflow_execution_service.swagger.yaml
```

```bash
Error parsing /work/ilmn/git/_other/workflow-execution-service-schemas/openapi/workflow_execution_service.swagger.yaml
bad indentation of a mapping entry at line 352, column 6:
         contact_info:
         ^
```

**Comment by jaeddy** [comment]
Thanks, @pr80ik. I fixed this bug in both #31 and #57, so should be resolved once either are merged into `develop`.

**Comment by pr80ik** [comment]
thx. can #63 be closed then?

**Comment by jaeddy** [comment]
I think so, but probably OK to wait until those PRs are merged, just to make sure.
