### ISSUE TITLE
Fill out the Product Approval Submission form

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/workflow-execution-service-schemas#74]
Background: https://docs.google.com/document/d/1UUJSnsPw32W5r1jaJ0vI11X0LLLygpAC9TNosjSge_w/edit#heading=h.tyqycskyykwh

The actual form: https://docs.google.com/forms/d/e/1FAIpQLScn8Rngp8DuH3XtUNSn4nsM8pPGlX9Ya9OuogLWTfzIhKsJNA/viewform

We can put the answers in the issues and then have one of us to fill out the form (since we can't group edit this).

**Comment by rishidev** [comment]
This was duplicated
