### ISSUE TITLE
Generate MD from Swagger

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#75]
To be included in the final document

**Comment by dglazer** [comment]
James addressed my review comments, and I approved, so #85 is ready to merge as far as I'm concerned.

**Comment by jaeddy** [comment]
Should I go ahead and merge? About to get on a plane, so can work on a few of the docs items/issues there.

**Comment by dglazer** [comment]
Yes, please do merge.
