### ISSUE TITLE
WES Publication Plan

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#76]
Plan for a 2-page application note style (Bioinformatics?)

**Comment by rishidev** [comment]
Publication and submission not needed, just the plan for the form

**Comment by jaeddy** [comment]
Planning to submit the [GA4GH/DREAM Workflow Execution Challenge](https://docs.google.com/document/d/1rUAQQXpc2b637jprxeWnKYt-Owc8FX_Q6cLw84KVZx8/edit) paper to F1000 sometime in the next couple months (hopefully before Basel).

Could reference WES and/or the testbed in this paper, or keep them separate.

**Comment by rishidev** [comment]
Yes, this is good
