### ISSUE TITLE
WES Reg and Ethics WS Form submitted

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#77]
A copy of the Regulartory and Ethics WS Product Approval form needs to be set up for the Cloud WS to work on and then submit as part of the Product Approval Submission.

**Comment by rishidev** [comment]
This questionnaire has now been prepared and is available to view at https://docs.google.com/document/d/103tH-9X1jTR2_tpOH6T041itJZsbtXrfO7b8ip9o4fc/edit?usp=sharing

**Comment by rishidev** [comment]
Updated with content

**Comment by briandoconnor** [comment]
@dglazer and I have an hour on our calendars on 8/21 to fill out the paperwork

**Comment by rishidev** [comment]
Submitted, received, Okayed and [has been approved](https://github.com/ga4gh/approval-tracker/issues/4)
