### ISSUE TITLE
RunDescription and RunStatus are identical - should they be collapsed?

### ISSUE THREAD

**Issue by geoffjentry** [ga4gh/workflow-execution-service-schemas#79]
Curious if anyone had thoughts on this.

For practical purposes `RunStatus` and `RunDescription` appear to be the same. Does anyone oppose collapsing them into a single entity?

@tetron @mckinsel @jaeddy ?

**Comment by mckinsel** [comment]
Seems fine to me; I think they're exactly the same?

**Comment by geoffjentry** [comment]
Technically they're not as one of them declares both fields as `REQUIRED` and one doesn't, but I can't imagine it ever being used otherwise in practical terms. I'm just going to open a PR instead of philosophizing here and then going through it again in PR form

**Comment by jaeddy** [comment]
Good catch, @geoffjentry. Not sure if `RunDescription` is ever used, and there's a `GetRunStatus` operation, so I'd vote for keeping that object. `RunStatus` seems to be missing a description/title, so maybe steal that from `RunDescription` before collapsing.
