### ISSUE TITLE
Fill out Product Approval Process form

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#83]
Need to fill out the [GA4GH Product Approval Submission](https://docs.google.com/forms/d/e/1FAIpQLScn8Rngp8DuH3XtUNSn4nsM8pPGlX9Ya9OuogLWTfzIhKsJNA/viewform) form when ready. This issue will be used to keep track of the information we will put in the form.

**Comment by rishidev** [comment]
Primary Work Stream - Cloud
Product Name - Workflow Execution Service
Product Version - v1.0.0
Source Driver Projects: HCA, Genomics England, TopMed
GitHub repository location: https://github.com/ga4gh/workflow-execution-service-schemas/

**Comment by rishidev** [comment]
Background: https://docs.google.com/document/d/1UUJSnsPw32W5r1jaJ0vI11X0LLLygpAC9TNosjSge_w/edit#heading=h.tyqycskyykwh

The actual form: https://docs.google.com/forms/d/e/1FAIpQLScn8Rngp8DuH3XtUNSn4nsM8pPGlX9Ya9OuogLWTfzIhKsJNA/viewform

**Comment by rishidev** [comment]
Product Background URL: https://docs.google.com/document/d/1EOU-Ku3sSB_Pbvdw-wxWFb9koya5Ql3esHW4uMPsLy8/edit?ts=5b3a3f15
Specification URL:  TODO - awaiting #75 to be completed
Product Landing Page: https://ga4gh.cloud

Product Maintainers TODO
1.
2.
3.

Journal Submission Plans: TODO #76 

Product Review Committee:
Marc Fiume, Aaron Kemp, Oliver Hofmann

Reg & Ethics URL: https://docs.google.com/document/d/103tH-9X1jTR2_tpOH6T041itJZsbtXrfO7b8ip9o4fc/edit#
Security URL: Original at https://docs.google.com/document/d/1_cqe80k_U_XjJSR4zP3ia4puxOirXVRcoJdMBwTeRGw/edit#heading=h.re5kk3dopqg1 (looks like follow up will not be needed)

**Comment by rishidev** [comment]
So elements awaiting confirmation for the form are listed here. Note that although a document URL is specified, it may not be complete within itself just yet.

Specification URL: TODO - awaiting #75 to be completed

Product Maintainers TODO
1.
2.
3.

Journal Submission Plans: TODO #76

**Comment by briandoconnor** [comment]
@dglazer and I have an hour on our calendars on 8/21 to fill out the paperwork

**Comment by rishidev** [comment]
Peter Amstutz, James Eddy and Jeff confirmed for Product Maintainers

**Comment by dglazer** [comment]
to be precise: @tetron @jaeddy @geoffjentry

**Comment by rishidev** [comment]
Publication plan text ready: "Our publication plan is to submit an application note to F1000 that details the WES API and links to work by our Driver Projects to implement and use the standard. We intend to submit the application note by the first half of 2019."

**Comment by rishidev** [comment]
Specification URL: TODO - awaiting #75 to be completed - the only outstanding item for the form

**Comment by dglazer** [comment]
The spec will be at https://ga4gh.github.io/workflow-execution-service-schemas/docs/ , once #75 is merged, run, and its output is merged. I expect @jaeddy will do that soon.

**Comment by rishidev** [comment]
Need to clarify implementation URLs and info for the form

**Comment by rishidev** [comment]
Completed
