### ISSUE TITLE
Address PRC Concerns: CANCEL and DELETE

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#95]
The PRC highlighted requested that the use of CANCEL be altered - desired behaviour in 6.4 of the PRC comments document  https://docs.google.com/document/d/1ul9Q_k5mwgzE1orrBsfb1mXrYyVWLDakGBeNyEmZQK0/edit

states:
- DELETE strikes me as a bit odd: once cancelled, I would still expect to be able to see the entity via listing or direct access.  As a comparative example, Google's Long Running Operations API has a similar structure but uses DELETE to remove the entity and provides a custom :cancel method to cancel the execution.
- A CANCEL op should hold the job / cancel operations, but retain run information for post-mortems. DELETE then can get rid of metadata / run information.

At the meeting the feeling was the specification can be amended to take this on board, but awaiting input from the spec maintainers (@mckinsel, @geoffjentry, @tetron, @denis-yuen) on this. The implementations do not need to be adjusted to account for this pre-Basel meeting.

**Comment by geoffjentry** [comment]
In the Cromwell API we have an `abort` endpoint (`POST`) which covers the same functionality. We explicitly didn't make it a `DELETE` for this reason, so I'm definitely 👍 on this (I'm AOK w/ `cancel`).

**Comment by tetron** [comment]
This sounds good to me as well.

**Comment by rishidev** [comment]
PRC happy with the modifications on this
