### ISSUE TITLE
Address PRC Concerns: WesObject 

### ISSUE THREAD

**Issue by rishidev** [ga4gh/workflow-execution-service-schemas#96]
The PRC highlighted requested that the use of WesObject be clarified. Section 7.11 of the PRC comments document https://docs.google.com/document/d/1ul9Q_k5mwgzE1orrBsfb1mXrYyVWLDakGBeNyEmZQK0/edit

states:
WesObject defined as “An arbitrary structured object.” Describe the difference between WesObject vs. string (application/json). Unify use of WesObject vs JSON input/output.
- Used for /runs outputs and for /run workflow_params, prefer fit-for-purpose Schemas. If nothing special, consider using string (application/json). 

At the meeting it was suggested the spec maintainers (@mckinsel, @geoffjentry, @tetron, @denis-yuen) can clarify this - if the WesObject is meant to be arbitrary string the change to string (application/json) should be made in a PR. If there are reasons for keeping WesObject they should be stated so that the reasoning can be communicated with the PRC.

 The implementations do not need to be adjusted to account for this pre-Basel meeting.

**Comment by geoffjentry** [comment]
I mentioned on the call yesterday that I thought `WesObject` was actually more of an artifact of history than seeds for something to come and that we should just get rid of it. In particular, my recollection is that we were viewing it as "this **should** be a JSON object, but giving ourselves wiggle room" type of thing.

I did some digging and do think that's true. 

It showed up in [this PR](https://github.com/ga4gh/workflow-execution-service-schemas/commit/c8e3980cc33542877ad062bf6f77bb7400237db1#diff-b1f8a5e75ad10e8057f21f2be2c37f66L342) and a) is an artifact of the old protobuf structure and b) definitely pays lip service to the JSON object thought.

I'd recommend either of the following, on a case by case basis:

- Making them strings
- Defining them as JSON objects

**Comment by rishidev** [comment]
PRC happy with the modifications on this
